menu title BBAI64 microSD - TI Processor SDK 10.00.00.08 (edgeai)

timeout 30

default sdk10

label sdk10
    kernel /Image
    fdt /k3-j721e-beagleboneai64-edgeai.dtb
    append console=ttyS2,115200n8 earlycon=ns16550a,mmio32,0x02800000 root=/dev/mmcblk1p2 rw rootfstype=ext4 rootwait cma=512M

label sdk10-plain-dtb
    kernel /Image
    fdt /k3-j721e-beagleboneai64.dtb
    append console=ttyS2,115200n8 earlycon=ns16550a,mmio32,0x02800000 root=/dev/mmcblk1p2 rw rootfstype=ext4 rootwait cma=512M
